name: Update README daily at 08:00

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '00 07 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Update README.md file
        run: node index.js
        env:
          CI: true
      - name: Check git diff
        run: |
          git diff
          git status
      - name: Debug token
        run: |
          if [ -z "${{ secrets.GH_TOKEN }}" ]; then
            echo "❌ GH_TOKEN est vide ou inexistant !"
          else
            echo "✅ GH_TOKEN existe (longueur: ${#GH_TOKEN})"
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Commit and push changes
        run: |
          git config --local user.name "Pierrelgx"
          git config --local user.email "pl.informatique47@gmail.com"
          git add README.md
          git diff --staged --quiet || git commit -m ":memo: README.md updated !"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/Pierrelgx/pierrelgx.git HEAD:main
